### ISSUE TITLE
FISH_INFO - clipApply codes

### ISSUE THREAD

**Issue by joneslabND** [MFEh2o/db#22] opened 2019-04-16 16:57 UTC
Some capitalization issues here also not sure what some codes are.  Need to convert 1's to anal fin (AF?)...

**Comment by cdassow** [comment] 2019-05-30 19:06
Current fin clip codes are , "LV"   "LC"   "LP"   "UC"   "RV"   "1"    "U"    "Lc"   ""     "anal", things to resolve, are U and UC the same? Change Lc to LC. Are 1's anal fin clips? (if the metadata is a fishscapes one then yes). Standardize anal fin clips/create an abbreviation for anal fin clips.

**Comment by kaijagahm** [comment] 2020-06-17 14:26
Changed Lc to LC. For rows where clipApply was "1" _and_ the metadataID was from Fishscapes, changed clipApply to "AF".

Remaining questions (@cdassow)
1. Is U the same as UC? Any idea how I can find out?
2. What should I do about non-fishscapes metadataID's when clipApply == "1"?
3. You said "Standardize anal fin clips/create an abbreviation for anal fin clips." Is that something that needs to be done through changes to a protocol, or is it simply a matter of changing the existing data in FISH_INFO?

**Comment by kaijagahm** [comment] 2020-06-30 14:45
Made some updates based on what Colin replied. More questions have now come up regarding tagApplyType and other related columns. I'm summarizing those here for @ctsolomon and @joneslabND to look over--what is the standard that we want to go by for this table?

This is a file of all the unique combinations of the columns useTagMarkRecap, tagApply, tagRecapture, tagApplyType, tagRecaptureType, clipApply, clipRecapture. I'd be happy to provide more information (sampleID's, fishID's, etc.) if you want it; I've just done this for now for brevity.
[tagcols.txt](https://github.com/MFEh2o/db/files/4852600/tagcols.txt)

A summary of the columns is as follows:
useTagMarkRecap takes "no", "yes", and NA.
tagApply takes many unique values, e.g. "900F224000104740". Also some like "178752324" and "2008003". Also some blanks and 1's.
tagRecapture takes the same types of values as tagApply.
tagApplyType takes the following values (this frequency table is from FISH_INFO, _not_ from the reduced text file I attached above):
`                LC left_pectoral_clip       lower_caudal  Lower_caudal_clip               none                pit 
               242                 14                 19                 25                 41               2307 
                UC       upper_caudal 
                35                 31 `

**Comment by ctsolomon** [comment] 2020-07-01 01:24
The original intention was for tagApply and tagRecapture to record applied and recaptured tag numbers, and tagApplyType and tagRecaptureType to record what type of tag that was (usually but not always PIT). For clips, the intention was to use a code to indicate which fin was clipped either in clipApply or clipRecapture. I think this is actually a pretty good model and I would be inclined to stick with it and just fix the errors that have crept in. It seems like a lot of the errors are simple controlled vocabulary issues that should be relatively easy to fix. A more complicated problem is when there is more than one tag type; the existing data model doesn't accommodate this very well. At any rate - now that you have laid out what the data issues look like I think we could resolve a lot of this (and describe the road ahead for the rest) pretty efficiently on our next call - or you could schedule a separate call with me, Stuart, and maybe Colin and Camille if you would prefer.

**Comment by kaijagahm** [comment] 2020-07-02 17:12
@ctsolomon @joneslabND it might be a good idea to schedule a separate call, especially if you think we should loop in Colin and/or Camille. I'll tag the four of you on Slack and we'll see what we can do.

**Comment by kaijagahm** [comment] 2020-07-13 11:54
We talked about this on the clipApply call and I think we came to a decision--keep in wide format, add columns, etc.

**Comment by kaijagahm** [comment] 2020-07-16 13:30
Colin's translation of fin clip codes is here: https://app.box.com/file/688861984708

**Comment by kaijagahm** [comment] 2020-07-21 16:14
Began to sort through these and apply the new format. Nobody knows what the deal is with the tagID column. First step could be to check the various intro documents, database vocab, etc. Chris remembers that there might be a sheet that specifically explains the fish info. 

Floy tag numbers should have a four-number year at the beginning--might help to sort it out if there are numbers that are ambiguous.

To do: grab the sampleID's for the fish where we don't have a PIT tag number and send them to Stuart.

**Comment by kaijagahm** [comment] 2020-07-22 12:16
@joneslabND Here's a text file of all the fish that have "pit" in tagApplyType but don't have a pit tag number. Let me know if you figure anything out about this!

[no_pit_number.txt](https://github.com/MFEh2o/db/files/4959870/no_pit_number.txt)

**Comment by kaijagahm** [comment] 2020-07-22 17:43
Made a google doc that includes the above-mentioned missing pit tag numbers, along with a bunch of other rows that have various types of problems (missing tag type or number, etc.). The google sheet is [FISH_INFO mystery tags](https://docs.google.com/spreadsheets/d/1xC92HvVOat1E2CYHZnIGRkDcWX3GRueXsotQLqjdsPU/edit?usp=sharing).

**Comment by kaijagahm** [comment] 2020-08-28 20:32
Following up on the results of the crowdsourced google doc: 
1. I added the information on the "fixed" sheet of the google doc (orange and blue rows).
2. I attempted to update the other rows according to Chris's comments at the bottom. Whenever there was uncertainty, I wrote the rows in question to csv files and uploaded them to the "Data sheets to check" google drive folder, adding them as to-do items in the README doc there. Hopefully checking the data sheets will help to clear this up.

**Comment by kaijagahm** [comment] 2020-10-13 14:55
Randi checked these data sheets. Need to implement the fixes.

**Comment by kaijagahm** [comment] 2020-12-07 21:45
@cdassow @joneslabND @ctsolomon Randi checked a bunch of these fish data sheets but couldn't find the 2009/2010 data sheets. More specifically, the fish in question are from Long, and the metadataID is MarkRecap.20120228, gear is AN.

Do we know where those data sheets are? Alternatively, is it safe to say that tags from those years would be floys? (Randi suspects so, but she isn't sure)

**Comment by joneslabND** [comment] 2020-12-07 21:55
How much data is associated with that? I don't think we should have any 2009 data and little or no 2010 data...

**Comment by kaijagahm** [comment] 2020-12-07 22:06
Looks like it's 11 fish from 2009 and 8 fish from 2010. Two sampleID's from 2010 and just one from 2009.

Beyond just these rows that I happened to run into because of the floy tag issue, I did a broader search in FISH_INFO for 2009/2010 samples. We have a total of 59 fish from 2009, from just one sampleID. We have a total of 179 fish from 2010, from five different sampleID's.

**Comment by kaijagahm** [comment] 2020-12-07 22:08
@Randinotte in your [fourDigitFloys_tocheck google spreadsheet](https://docs.google.com/spreadsheets/d/1zwd-cPpvGUTMzTFtfDp6ZvyidN4jGqUJj8CZXFTMZjw/edit#gid=492825326), you flagged two fish that had the wrong fish number based on the data on the original data sheets. One of them had fishNum == 1, but it should have been fish 3 based on the data sheet; the other had fishNum == 3, but it should have been fish 9 based on the data sheet.

The thing is, for each of those fish, there is already a different fish taking up the other number in that sampleID. So, there's already a fish 3 and a fish 9, respectively. They aren't duplicates.

Do you see any reason why we have to fix this? i.e. is it okay to keep the numbers as they are (presumably based on the order in which they were tagged, according to your own notes), and rely on the weights/lengths to distinguish them if there's ever a question? Or do you think we need to trace this forward and correct the numbers?

**Comment by ctsolomon** [comment] 2020-12-08 01:18
Re 2009 - I think Weidel might have had some fish data from that year that he threw in to the database early on, even though we didn't have our own field crew there back then.

**Comment by joneslabND** [comment] 2020-12-08 02:18
seems like that is the case based on the crew listing

**Comment by Randinotte** [comment] 2020-12-08 20:53
@kaijagahm I'm not sure why they would have entered the sheet out of order, but so long as the correct data is associated with unique fish, I don't think figuring out the exact fishNum is necessary.

**Comment by kaijagahm** [comment] 2020-12-08 21:27
Okay, good. @Randinotte I'm going to leave those fish numbers alone, since I don't see any overlapping data or duplicates. @joneslabND and @ctsolomon, based on what we talked about today, I'm going to go ahead and call those 2009/2010 tags floys and be done with it.

**Comment by kaijagahm** [comment] 2020-12-10 19:51
Finished making these corrections.

Went through each of the columns we were going to remove and took my best guess for the remaining ones about how to fix it. When I couldn't tell, I left a comment (e.g. if the columns conflicted as to whether the tag was a recap or an apply).

I'll just need to re-run this script through one more time once Randi finishes with her update, before calling this good.

**Comment by kaijagahm** [comment] 2020-12-10 19:53
More checks to do before I'm done:
- For any fish that has a number in either floyApply or pitApply, check that that tag number doesn't turn up in any earlier entries
- For any fish that has a number in either floyRecapture or pitRecapture, check that the tag number DOES turn up in an earlier entry.
- Could take this opportunity also to check that the fishNum matches the number portion of the fishID
- Check for any duplicate fishID's
- Check for any duplicate tag numbers on different fish [oh, interesting--does this mean we should put the tagID column back and fill it with a number, irrespective of the type of tag? This could have something to do with why it was set up this way in the first place.]

**Comment by kaijagahm** [comment] 2020-12-18 21:04
> * For any fish that has a number in either floyApply or pitApply, check that that tag number doesn't turn up in any earlier entries

Actually going to punt this one over to #99 and not deal with it here.

**Comment by kaijagahm** [comment] 2020-12-18 21:06
> * For any fish that has a number in either floyApply or pitApply, check that that tag number doesn't turn up in any earlier entries
> * For any fish that has a number in either floyRecapture or pitRecapture, check that the tag number DOES turn up in an earlier entry.

Actually going to punt this one over to #99 and not deal with it here.

**Comment by kaijagahm** [comment] 2020-12-18 21:34
> * Check for any duplicate tag numbers on different fish [oh, interesting--does this mean we should put the tagID column back and fill it with a number, irrespective of the type of tag? This could have something to do with why it was set up this way in the first place.]

Also punting this one to a different issue: #104

**Comment by kaijagahm** [comment] 2020-12-18 21:37
> * Could take this opportunity also to check that the fishNum matches the number portion of the fishID
> * Check for any duplicate fishID's

I checked both of these, and they're both all set. Hooray!

**Comment by kaijagahm** [comment] 2020-12-24 21:44
Was progressing nicely through creating a meta document for this database update, and then I ran across an error in FISH_SAMPLES, caused by a stray case_when() statement in Randi's code from the last update, that caused most of the updateID's in FISH_SAMPLES to revert to NA. 

Finalizing this issue, and creating the meta script for the database update, is on hold until I can talk to Randi about it.

**Comment by kaijagahm** [comment] 2021-02-17 20:06
Fixed in database update 4.4.0

**Closed by kaijagahm** 2021-02-17 20:06 UTC
Labels: ready for db update

**Comment by kaijagahm** [comment] 2021-06-18 21:18
Cleaning out my google drive. Here's an Excel version of the spreadsheet that we used, interactively, to try to correct tag numbers and assign tag types to them.
[FISH_INFO mystery tags.xlsx](https://github.com/MFEh2o/db/files/6679400/FISH_INFO.mystery.tags.xlsx)

**Comment by kaijagahm** [comment] 2021-06-18 21:20
Oh, and here are some notes we took about what to do with the clip and tag formats. We settled on the current wide format with pitApply, pitRecapture, floyApply, floyRecapture.
[FISH_INFO_ clip and tag apply columns discussion notes.docx](https://github.com/MFEh2o/db/files/6679410/FISH_INFO_.clip.and.tag.apply.columns.discussion.notes.docx)
