### ISSUE TITLE
FISH_INFO duplicated fishID

### ISSUE THREAD

**Issue by ctsolomon** [MFEh2o/db#29] opened 2019-06-10 14:37 UTC
There are duplicated fishIDs in the FISH_INFO table. This happened as a result of the way we were taking data for 2018 crangling - I think if two different people fished in the same boat they got the same sampleID and thus their fish 1, fish 2, etc each ended up with duplicated fishID. Colin, Chris, and Stuart talked in June 2019 about resolving this - the new crangling data protocol should resolve the problem in future. But we should go back and correct 2018 fishIDs accordingly. 

I am pasting below a bit of code that I used to confirm that this problem exists.

It would be worth double-checking that there are not duplicated fishIDs in other parts of the FISH_INFO table - I only checked 2018 since that's when we thought the problem occurred.

#Check for duplicates in 2018 crangling fishIDs
#CTS 2019-06-10

library(lubridate)

#Load MFE db utilities
source('dbUtil.r')

#Directory for db
dbDir # <-  file path to where database is stored on your local machine

#Load tables
fishInfo <- dbTable('FISH_INFO', fpath=dbDir)
fishSamples <- dbTable('FISH_SAMPLES',fpath=dbDir)

#Select from fishSamples those samples that were  in 2018
length(which(is.na(fishSamples$dateTimeSample)))
fishSamples <- subset(fishSamples,year(fishSamples$dateTimeSet)==2018)

#Select from fishInfo those rows that are in this set of 2018 samples
fishInfo <- subset(fishInfo,fishInfo$sampleID%in%fishSamples$sampleID)

#Check for duplicates in fishID in this reduced fishInfo
any(duplicated(fishInfo$fishID))
#Looks like there are duplicates. Which ones?
dups <- which(duplicated(fishInfo$fishID)==T)

#Take a look at the first of these to confirm that it is actually duplicated
dups[1]
fishInfo[1:6,]
#Yes, duplicates are present

**Comment by kaijagahm** [comment] 2020-06-12 21:23
There are indeed duplicates in 2018; however, there are also a few duplicates from 2016, 2017, and 2012. Some of these have all but one cell the same, in which case it's probably straightforward to delete the row with less information. Others have contradictory information (e.g. different species of fish). Should check whether this is a correction, or actually different fish.

Need to decide what to do to fix the duplicate fishID's for the abovedescribed 2018 protocol. Chris says "we should go back and correct 2018 fishIDs accordingly." What does that mean?

Next:
- Check the overview doc for how sampleID's and fishID's are assigned, and see if the correction is obvious. 
- Continue looking for the 2018 crangling protocol document.
- If no leads, ask.

**Comment by kaijagahm** [comment] 2020-06-15 12:51
Randi is checking with Colin to see if we can find the new crangling data protocol, which may provide guidance on how to update fishID's to resolve duplicates.

**Comment by kaijagahm** [comment] 2020-06-15 13:38
Talked to Colin: 6/15 morning. He is looking for the Fishscapes.Angling.20180625 file (has emailed Alex). This would have the revised protocol.

Over the call, Colin confirmed that the only change that needs to be made is updating the fish numbers, so if we had 1-5 for one person in the boat, and 1-5 for another person in the boat, those should become 1-10 (unique number for each fish). The order doesn't particularly matter, and the fish numbers are pretty arbitrary. There should also be a column for who caught the fish. Colin says that should already be filled out, but I'll double check.

Should make sure to check that the fishID's don't link to another table, or if they do, that the link is correct. 

EDIT 16 June 2020: Colin has re-written Fishscapes.Angling.20180625.pdf and put it on Box.
[Fishscapes.Angling.20180625.docx](https://github.com/MFEh2o/db/files/6870217/Fishscapes.Angling.20180625.docx)

**Comment by kaijagahm** [comment] 2020-06-15 14:06
For the 2018 duplicates: It looks like the renumbering that Colin was discussing was already carried out halfway. The fish with duplicate fishID's seem to have unique fishNum's. This screenshot illustrates an example: you can see how the numbers at the end of the fishID's go from 1 to 17 and then start over, but the corresponding numbers in the fishID column go up incrementally and continuously, without starting over.

![Screen Shot 2020-06-15 at 10 02 16](https://user-images.githubusercontent.com/37053323/84666682-64378b80-aeef-11ea-8602-b5f12e2ceff9.png)

I think all that I need to do here is change the number at the end of each fishID so it matches the number in the fishNum column. Before I do that, I'm going to check to make sure there aren't any rows where both the fishID and the fishNum column are the same.

**Comment by kaijagahm** [comment] 2020-06-15 16:31
Fixed duplicate fishID's for all 2018 fish. Going to close this issue now and punt the remaining duplicated fishID's over to #38 (because they're not from 2018).

**Comment by kaijagahm** [comment] 2020-06-15 16:37
Fixed all of the 2018 duplicated fishID's by re-numbering. Checked the other duplicates to make sure they were present in the csv file––they were. So I don't think we should worry about data being overwritten. Removed any remaining _full_ duplicates. For remaining non-full duplicates, removed two cases where rows were identical except for an NA in a column for one row where the other row had information there––kept the row with more information. 

There are still some duplicates remaining. These might be different fish that somehow got assigned the same ID, or in some cases, they might be the same fish with different information (mistakes?). For an example of the latter, see the first two rows of the attached file: looks like the same fish, but in one row the length is 173, and in the other it's 73. 

Next: going to investigate these by pulling up all records for the sampleID. Seems like in most cases the fish were just misnumbered, and I can just assign new numbers.

**Comment by kaijagahm** [comment] 2020-06-15 17:07
Fixed numbers for several of the remaining duplicates, and assigned updateID's. 

We have three remaining pairs of duplicates, which I've flagged because they could possible be the same fish, measured twice or something.

The first pair seems like a pretty straightforward measurement error: everything is the same except for the fishLength, which is 173 in one case and 73 in the other case. I think one of these rows should be deleted, but I don't know which one.

The second and third pairs are less straightforward. I think it's likely that we have four different fish, and that I should just renumber, like I did with the others. But I've flagged these because the species is the same and the measurements are close to being the same, and additionally, there are no other records for these sampleID's. So for each of these sampleID's, either 1) only two fish were caught, they happened to be very similar in size, and they each got accidentally assigned the same number, or 2) there's something else going on, such as a re-measurement of one fish that got its own sampleID for some reason? Not sure.

(This is a comma-separated text file, because for some reason I can't upload a csv to GH issues.)
[remaining_dup_fishIDs.txt](https://github.com/MFEh2o/db/files/4781793/remaining_dup_fishIDs.txt)

**Comment by cdassow** [comment] 2020-06-15 17:33
Hey kaija, I'm pretty sure you're right on the first one with the 173 and 73. I would say we should double check the paper copy which is in the lab on campus here since it's entirely likely that in the same net we caught both a 173 and a 73 bluegill and maybe the typo was in the fish num and not the lengths. However if that were the case then their gonad weights should be quite different (but the aren't) since one is so much larger.

For the other two I bet the WL minnow trap fish are two different fish and this should be renumbered. For the FE minnow trap I agree that could be the same fish that got remeasured and entered again for some reason

I'll put checking the paper data sheets for all these on my list of things to do when I'm back in town, if I don't get to it tomorrow.

**Comment by kaijagahm** [comment] 2020-06-23 19:59
@cdassow has now checked for these data sheets.

**Comment by kaijagahm** [comment] 2020-07-06 13:06
Asked Chris about the 173/73 fish--data sheet might be at Cary.

Randi checked the spreadsheet version (not the original paper data sheet) and we think these are two different fish: file is "longMinnow_2018.xlsx" in MFE/OneDriveArchive/Summer2018/Summer 2018/fishLogs/longMinnow_2018.xlsx.

**Comment by cdassow** [comment] 2020-07-06 14:26
Still tracking down the 2018 binder, Carly thinks it might be in her office

**Comment by kaijagahm** [comment] 2020-07-06 20:56
Update: @cdassow tracked down the 2018 binder, and those are indeed two separate fish.

So the only remaining problem is the 173/73 length fish. Binder may be at Cary. Chris is going to check in the next couple weeks--follow up with him if he hasn't gotten back to me in ~2 weeks.

**Comment by kaijagahm** [comment] 2020-07-10 18:07
Chris had someone check, and they didn't immediately find the binder. Going to have to stall this issue for now, until/unless we can resolve it.

**Comment by kaijagahm** [comment] 2020-11-05 15:51
Photo for the sampleID BG_FNbig_20160615_1255_FN_GonadSurvey.20160623:
![20160615 1255 BG FNbig](https://user-images.githubusercontent.com/37053323/98263409-c9e6eb80-1f54-11eb-9b3b-842f98b6824a.jpg)

**Comment by cdassow** [comment] 2020-11-05 16:19
Looks to me like the typo may have been in the fish length. This picture looks to me like a clear 73mm BLG for fish number 8. Also, given the weight of 5.6 grams I think that's a safe bet. If you look at the 172 BLG at fish number 2 it's weight 83.5 grams so I'd expect the weight of fish 8 to be about that if it's length really was 173.

Thanks @kaijagahm and/or @ctsolomon for tracking this down!

**Comment by kaijagahm** [comment] 2020-11-13 22:31
Fixed that final duplicated fishID. Moved the code over to the script for #93 and #92 so we wouldn't have to do a bunch of separate database updates to deal with the fish tables.

This is ready for the db update.

**Comment by kaijagahm** [comment] 2020-11-25 21:40
Fixed in v 4.1.0

**Closed by kaijagahm** 2020-11-25 21:40 UTC
Labels: ready for db update
