### ISSUE TITLE
BENTHIC_INVERTS metadata

### ISSUE THREAD

**Issue by ctsolomon** [MFEh2o/db#32] opened 2019-07-03 14:19 UTC
There are a few problems with the metadata in BENTHIC_INVERTS:

- There are a couple rows of the metadataID column where metadataID is "".
- There is both a "zoobenthos.Sample.20181114" and a "zoobenthosSample.20181114" in the metadataID column.
- Originally I think our intention was for zoobenthos sampling methods to be described by a sampling metadata in the SAMPLES table, and zoobenthos processing methods to be described by a different metadata (zoobenthosLengths) in the BENTHIC_INVERTS table. Did this get lost? Should it be resurrected?
- We should make sure the metadata descriptions kept pace with changing methods. For instance, metadataID "zoobenthosLengths.20110519" says that chironomids were identified on a microscope slide; I think we may have stopped using this method earlier than the metadata reflect.

**Comment by ctsolomon** [comment] 2020-02-20 00:13
There is also some confusion between "zoobenthos.Sample.20110714" and "BenthicInvert.Sample.20110714" about the area sampled. For both the push corer and the Ekman these two metadata descriptions give slightly different areas. I suspect that maybe the "BenthicInvert.Sample.20110714" has the correct areas;  the first line on the associated Word document describes this as an "ammendment to BenthicInvert.Sample.20110714", and these areas also match what Nikki Craig's thesis says. We should clarify and clean up. Note also that "BenthicInvert.Sample.20110714" specifies a few dates on which 1 m samples were taken with Ekman instead of cores (and so area sampled is different); consider making a comment in the comments column of the samples table, if there isn't already one there?

**Comment by kaijagahm** [comment] 2020-06-16 19:14
As of today, I've fixed the spelling error (Chris's second bullet point above). See #49.

Re: bullet point 1––because of the code that I added to the dbTable function, which converts "NA" and "" to NA (https://github.com/MFEh2o/db/commit/1ebef06a931b980dd55e7c08fcc66ab33377ba21), those two rows now have NA for metadataID instead of "". This is still a problem.

**Comment by kaijagahm** [comment] 2020-06-17 14:12
See #33 as well––looks like the structure with different metadataID's for each table is correct. But the question is, which one should be included in the sampleID? Presumably should be the one relating to the sampling methodology.

**Comment by kaijagahm** [comment] 2020-09-14 15:46
> Re: bullet point 1––because of the code that I added to the dbTable function, which converts "NA" and "" to NA ([1ebef06](https://github.com/MFEh2o/db/commit/1ebef06a931b980dd55e7c08fcc66ab33377ba21)), those two rows now have NA for metadataID instead of "". This is still a problem.

Fixed this in #62.

This issue is now basically a duplicate of #33. Going to close it and work on the issue over there.

**Closed by kaijagahm** 2020-09-14 15:46 UTC
Labels: BENTHIC_INVERTS
